version: 2

models:
  - name: stg_btc
    columns:
      - name: hash_key
        data_tests:
          - unique
          - not_null
  
  - name: stg_btc_outputs_col
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_col_py')
  
  - name: whale_alert
    latest_version: 2
    config:
      contract:
        enforced: true
    columns:
      - name: outputs_address
        data_type: string
        data_tests:
          - assert_valid_btc_address
      - name: total_sent
        data_type: float
      - name: tx_count
        data_type: int
      - name: total_sent_usd
        data_type: float
    versions:
      - v: 1
        deprecation_date: 2026-02-01
        config:
          enabled: false
      # Matches what's above -- nothing more needed
      - v: 2
      # Removed a column -- this is the breaking change!
        columns:
        # This means: use the 'columns' list from above, but exclude country_name
          - include: all
            exclude: [total_sent_usd]