version: 2

sources:
  - name: btc
    database: btc
    schema: btc_schema
    tables:
      - name: btc_table
        config:
          loaded_at_field: block_timestamp
          freshness:
            warn_after: {count: 1, period: 'hour'}
            error_after: {count: 3, period: 'hour'}